### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by xificurC** [metosin/malli#123]
Hi, I'm playing with malli in a project and would need to know the license.

On a different note, I started thinking about the license because there's basically no releases of the library and the one on clojars is missing a fix I need, so I was thinking of inlining the source code into my source tree. Would it be possible to every now and then bump a number and release on clojars?

**Comment by esuomi** [comment]
This is a very good point! Very quick summary of how software licensing matters for places where it matters:

 - _unlicensed_ means _unusable_ as the author has not given any rights over to potential users
 - having a license of course means the code is licensed accordingly; up to author(s) what they choose, but it is equally important to understand that _the license exists only from that specific commit onwards_ and license cannot be "backported" or revoked without proof of violation
 - Additionally, _do not add a year next to license/copyright mark._ Trouble with this is that if you add it, it has to be kept up to date or it means it is valid _up to but not beyond_ that year; also open-ended ranges (eg. 2016- or "since 1985") are not valid as licensing isn't from legal point of view valid if its applicability is ambigious

All this learned from having a few drinks with a few copyright/privace lawyers a few years back... :) So please indeed, add license ASAP! :)

**Comment by mikeananev** [comment]
@ikitommi , hi. Please, add the license to malli.

Thanks.

**Comment by miikka** [comment]
Hi, we will license Malli under [EPL-2.0](https://spdx.org/licenses/EPL-2.0.html#licenseText) (the same license that most Metosin libraries use; it's an updated version of the license Clojure uses). However, we're in the awkward situation where we have accepted contributions before adding the license. I've reached out to all the contributors via e-mail to confirm that they agree with this license and I'll add the license once I've gotten a reply from everyone.

**Comment by miikka** [comment]
@kmwang and @loomis – I already sent you an e-mail about this but I'm posting this here in case a Github notification reaches you better. We want to license Malli under Eclipse Public License 2.0 (EPL-2.0) and I need the confirmation from both you:

Do you license your contributions to Malli under EPL-2.0? In case the contributions were part of work you did for an employer or a client, do you have their permission to license it?

**Comment by loomis** [comment]
@miikka Sorry, I didn’t get the email, but got the notification. To be explicit, I agree to licence my contributions under the EPL-2.0 license. My contributions were my own work and were not done on behalf of an employer or client.

**Comment by kmwang** [comment]
@miikka Sorry. It took me a while to get my company's approval on this. In short, yes, we agree to license my contributions under EPL-2.0. Thanks.

**Comment by miikka** [comment]
We've now gotten confirmations from all the non-Metosin contributors (Arne Brasseur, Charles Loomis, Jean Boudet, Ryan Schmukler, and Søren Sjørup) that they license their contributions under EPL-2.0. Thanks to everybody for the contributions and for the quick coöperation!

I'll add the licensing information to the repo and close the issue.
